build: client.cpp ../SocketManager.hpp ../ClientManager.hpp ../shared.hpp
	g++ -o client client.cpp
	
run: client
	./client
	
run: client.cpp ../SocketManager.hpp ../ClientManager.hpp ../shared.hpp
	g++ -o client client.cpp
	./client
	
clean:
	rm a.out
	
cleanAll:
	rm a.out
	rm client