build: server.cpp ../SocketManager.hpp ../ServerManager.hpp ../shared.hpp
	g++ -o server server.cpp
	
run: server
	./server
	
run: server.cpp ../SocketManager.hpp ../ServerManager.hpp ../shared.hpp
	g++ -o server server.cpp
	./server
	
clean:
	rm server